[colors.bright]
black = "0x6e6a86"
blue = "0x31748f"
cyan = "0xebbcba"
green = "0x9ccfd8"
magenta = "0xc4a7e7"
red = "0xeb6f92"
white = "0xe0def4"
yellow = "0xf6c177"

[colors.cursor]
cursor = "0x825B65"
text = "0x232136"

[colors.hints.end]
background = "#393552"
foreground = "#59546d"

[colors.hints.start]
background = "#393552"
foreground = "#817c9c"

[colors.line_indicator]
background = "None"
foreground = "None"

[colors.normal]
black = "0x817c9c"
blue = "0x3e8fb0"
cyan = "0xea9a97"
green = "0x9ccfd8"
magenta = "0xc4a7e7"
red = "0xeb6f92"
white = "0xe0def4"
yellow = "0xf6c177"

[colors.primary]
background = "0x232136"
foreground = "0xe0def4"

[colors.selection]
background = "0x312E45"
text = "CellForeground"

[colors.vi_mode_cursor]
cursor = "0x825B65"
text = "0x191724"
