PORTNAME=		    wayfire-desktop-developer
PORTVERSION=	    1.0.0
CATEGORIES=		    x11-wm
DISTNAME=		    ${PORTNAME}-${ISCVERSION}
DISTVERSIONPREFIX=	v

MAINTAINER=		    mark@cloudbsd.org
COMMENT=		    Instantly installs a Wayfire desktop environment with developer tools
WWW=			    https://github.com/cloudbsdorg/wayfire-desktop-developer

LICENSE=		    BSD2CLAUSE

RUN_DEPENDS=		wayfire-desktop:x11-wm/wayfire-desktop

MASTER_SITES=		GH
USE_GITHUB=		    yes
GL_SITE=		    https://github.com
GH_ACCOUNT=		    cloudbsdorg
GH_PROJECT=		    wayfire-desktop-developer

.include <bsd.port.mk>